version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: birthday
      MYSQL_USER: root
      MYSQL_PASSWORD: example_password
      MYSQL_DB: birthday_db
    depends_on:
      - birthday
  birthday:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: birthday_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: